Repository seL4/camkes-vm-examples, pull requests merged in 2024-01, with the labels that each got.

#53 README: bring build instructions up to date
  README.md
Labels: docs

#60 CI: support hardware build and test for PRs
  .github/workflows/test-hw.yml
Labels: CI

#61 CI: the seL4/machine_queue repo is public now
  .github/workflows/camkes-vm-deploy.yml
Labels: CI

#51 x86, minimal_64: use hpet
  apps/x86/minimal_64/app_settings.cmake
Labels: hw-test

#62 CI: use commits from PR and not from master
  .github/workflows/test-hw.yml
Labels: bug, CI

#63 github: update GitHub actions
  .github/workflows/camkes-vm-deploy.yml
  .github/workflows/test-hw.yml
Labels: CI

#45 Copy timestamp of icmp data field
  apps/Arm/vm_virtio_net/components/PingClient/ping_client.c
Labels: bug, hw-test

#70 CI: pick unique name for deployment workflow
  .github/workflows/camkes-vm-deploy.yml
Labels: CI

#57 vm_virtio_net: add zcu102 support
  apps/Arm/vm_virtio_net/CMakeLists.txt
  apps/Arm/vm_virtio_net/overlay_files/init_scripts/zynqmp/arping_test
  apps/Arm/vm_virtio_net/overlay_files/init_scripts/zynqmp/ping_test
  apps/Arm/vm_virtio_net/settings.cmake
  apps/Arm/vm_virtio_net/zcu102/2022_1/devices.camkes
Labels: hw-test
